import { useEffect, useState, useContext } from 'react'
import Head from 'next/head'
import { 
  Container, 
  Box,
  Center,
  Text
} from '@chakra-ui/react'

import LoginBox from '../components/LoginBox/LoginBox'
import AuthContext from '../context/AuthContext'

export default function Home() {

  const { user } = useContext(AuthContext)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW='1200px' h='100vh' centerContent>
        <Center h='100%'>
          { user ? <Text>Welcome {user.username} </Text> : <LoginBox />}
        </Center>
      </Container>
    </> 
  )
}
