import Head from 'next/head'
import { 
  Container, 
  Box,
  Center
} from '@chakra-ui/react'

import LoginBox from '../components/LoginBox/LoginBox'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW='1200px' h='100vh' centerContent>
        <Center h='100%'>
          <LoginBox />
        </Center>
      </Container>
    </> 
  )
}
