import { useEffect, useState, useContext } from 'react'
import Head from 'next/head'
import {
    Center,
    Container,
    Stack
} from '@chakra-ui/react'
import { useRouter } from 'next/router'

import LoginBox from '../components/LoginBox/LoginBox'
import Navbar from '../components/Navbar/Navbar'
import FriendsList from '../components/FriendsList/FriendsList'
import RoomListFeed from '../components/RoomListFeed/RoomListFeed'
import ProfileUpcomingRoomsSection from '../components/ProfileUpcomingRoomsSection/ProfileUpcomingRoomsSection'
import AuthContext from '../context/AuthContext'

export default function Login() {
    const { user } = useContext(AuthContext)
    const router = useRouter()

    useEffect(() => {
        if (!user) {
            console.log('user not logged in')
            router.push('/login')
        }
    }, [user])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <Container maxW='1320px' w='100%' mb={6} centerContent p={0}>
                <Stack direction='row' w='100%' spacing='60px'>
                    <FriendsList />
                    <RoomListFeed />
                    <ProfileUpcomingRoomsSection />
                </Stack>
            </Container>
        </>
    )
}

// MYPETS 

// import {
//     useState
// } from 'react'
// import { 
//   Container, 
//   Flex, 
//   useToast 
// } from "@chakra-ui/react"

// import AnnouncementBanner from '../components/AnnouncementBanner/AnnouncementBanner'
// import Navbar from '../components/Navbar/Navbar'
// import SortMenu from '../components/SortMenu/SortMenu'
// import MerchantSectionList from '../components/MerchantSectionList/MerchantSectionList'
// import ProductSectionList from '../components/ProductSectionList/ProductSectionList'
// import CategoryList from '../components/CategoryList/CategoryList'
// import HomeBannerSwiper from '../components/HomeBannerSwiper/HomeBannerSwiper'
// // import { API_PRODUCTS_URL, API_MERCHANTS_URL } from '../utils/urls'

// export default function Home() {

//     const merchants = [
//     {
//         name: 'Macho pawz',
//         rating: 4.8,
//         display_image: 'https://mypets-images.s3.ap-southeast-1.amazonaws.com/macho_pawz_logo_282x264_2x_fc5703e865.png',
//         slug: 'macho-pawz'
//     },
//     {
//         name: 'Macho pawz',
//         rating: 4.8,
//         display_image: 'https://mypets-images.s3.ap-southeast-1.amazonaws.com/macho_pawz_logo_282x264_2x_fc5703e865.png',
//         slug: 'macho-pawz'
//     },
//     {
//         name: 'Macho pawz',
//         rating: 4.8,
//         display_image: 'https://mypets-images.s3.ap-southeast-1.amazonaws.com/macho_pawz_logo_282x264_2x_fc5703e865.png',
//         slug: 'macho-pawz'
//     },
//     {
//         name: 'Macho pawz',
//         rating: 4.8,
//         display_image: 'https://mypets-images.s3.ap-southeast-1.amazonaws.com/macho_pawz_logo_282x264_2x_fc5703e865.png',
//         slug: 'macho-pawz'
//     },
//     {
//         name: 'Macho pawz',
//         rating: 4.8,
//         display_image: 'https://mypets-images.s3.ap-southeast-1.amazonaws.com/macho_pawz_logo_282x264_2x_fc5703e865.png',
//         slug: 'macho-pawz'
//     },
//     {
//         name: 'Macho pawz',
//         rating: 4.8,
//         display_image: 'https://mypets-images.s3.ap-southeast-1.amazonaws.com/macho_pawz_logo_282x264_2x_fc5703e865.png',
//         slug: 'macho-pawz'
//     }
// ]

//     const pageProducts = [
//         {
//             name: "Sensitive Skin Formula [Dog]",
//             rating: 5,
//             merchant: {
//                 name: "Macho Pawz"
//             },
//             slug: 'sensitive-skin-formula-dog',
//             image: 'https://mypets-images.s3.ap-southeast-1.amazonaws.com/12_DIAMOND_CARE_ae4edcdc06.jpg'
//         },
//         {
//             name: "Fresh Breath Oral Gel [Dogs]",
//             rating: 5,
//             merchant: {
//                 name: "Macho Pawz"
//             },
//             slug: 'sensitive-skin-formula-dog',
//             image: 'https://mypets-images.s3.ap-southeast-1.amazonaws.com/34_TROPICLEAN_c1fbe791a6.jpg'
//         },
//         {
//             name: "Venison & Legumes [Dog]",
//             rating: 5,
//             merchant: {
//                 name: "Macho Pawz"
//             },
//             slug: 'sensitive-skin-formula-dog',
//             image: 'https://mypets-images.s3.ap-southeast-1.amazonaws.com/6_TASTE_OF_THE_WILD_5fe7593f8f.jpg'
//         },
//         {
//             name: "Senior Poultry [Dog]",
//             rating: 5,
//             merchant: {
//                 name: "Macho Pawz"
//             },
//             slug: 'sensitive-skin-formula-dog',
//             image: 'https://mypets-images.s3.ap-southeast-1.amazonaws.com/14_EUKANUBA_746031f139.jpg'
//         },
//         {
//             name: "Small Breed Adult Lamb & Potato [Dog]",
//             rating: 5,
//             merchant: {
//                 name: "Macho Pawz"
//             },
//             slug: 'sensitive-skin-formula-dog',
//             image: 'https://mypets-images.s3.ap-southeast-1.amazonaws.com/13_BOW_WOW_ZENITH_d9f04e629a.jpg'
//         },
//         {
//             name: "Venizon & Garbanzo Beans [Dog]",
//             rating: 5,
//             merchant: {
//                 name: "Macho Pawz"
//             },
//             slug: 'sensitive-skin-formula-dog',
//             image: 'https://mypets-images.s3.ap-southeast-1.amazonaws.com/5_TASTE_OF_THE_WILD_59a89d5055.jpg'
//         },
//         {
//             name: "Turkey Tendon Strips [Dogs]",
//             rating: 5,
//             merchant: {
//                 name: "Macho Pawz"
//             },
//             slug: 'sensitive-skin-formula-dog',
//             image: 'https://mypets-images.s3.ap-southeast-1.amazonaws.com/22_AFRESHCI_65dd6414ef.jpg'
//         },
//     ]

//     const [sortMethod, setSortMethod] = useState('pop')
//     const [selectedCategory, setCategorySelected] = useState('All products')
//     const categories = [
//         'All products',
//         'Treats',
//         'Dry food',
//         'Wet food',
//         'Supplements',
//         'Toys'
//     ]

//   return (
//     <>
//         <AnnouncementBanner />
//         <Navbar user={true}/>
//         <Container 
//             maxW={{ lg: "1200px" }} 
//             mb={4}
//             p={{ base: 4 }}
//             // bg='blue.100'
//         >   
//             <HomeBannerSwiper my={{ base: 8, md: 16 }} rounded={{ base: 20, md: 40 }} bg='green.100'/>
//             <Flex justifyContent='space-between' direction="row" 
//                 // bg='red.100'
//             >
//                 <Flex direction="column" w="100%">
//                     <MerchantSectionList merchants={merchants} />
//                     <Flex direction={{ base: 'column', lg: 'row'}} w='100%'>
//                         <ProductSectionList 
//                             products={pageProducts} 
//                             categories={categories}
//                             sortMethod={sortMethod} 
//                             selectedCategory={selectedCategory}
//                             setCategorySelected={setCategorySelected} 
//                             heading='Recommended Products' 
//                         />
//                         <Flex direction='column' w='210px' ml={12} mt={12} display={{ base: 'none', lg: 'inherit' }} >
//                             <SortMenu setSortMethod={setSortMethod} />
//                             <CategoryList categories={categories} setSelectedCategory={setCategorySelected} />
//                         </Flex>
//                     </Flex>
//                 </Flex>
//             </Flex>
//         </Container>
//     </>
//   )
// }



